export const ADD_FIRST_NAME="ADD_FIRST_NAME";
export const ADD_LAST_NAME="ADD_LAST_NAME";
export const ADD_CITY_NAME="ADD_CITY_NAME";
export const ADD_BIRTH_DATE="ADD_BIRTH_DATE";
export const ADD_EMPLOYMENT="ADD_EMPLOYMENT";
export const SUBMIT_PASSWORD="SUBMIT_PASSWORD";