export const ADD_REGIS_EMAIL="ADD_REGIS_EMAIL";
export const ADD_FIRST_NAME="ADD_FIRST_NAME";
export const ADD_LAST_NAME="ADD_LAST_NAME";
export const ADD_CITY_NAME="ADD_CITY_NAME";
export const ADD_BIRTH_DATE="ADD_BIRTH_DATE";
export const ADD_EMPLOYMENT="ADD_EMPLOYMENT";
export const ADD_REGIS_PASSWORD="ADD_REGIS_PASSWORD";
export const REGISTER_REQUEST="REGISTER_REQUEST";