export const CHECK_FIRST_BOX="CHECK_FIRST_BOX";
export const CHECK_SECOND_BOX="CHECK_SECOND_BOX";
export const UNCHECK_FIRST_BOX="UNCHECK_FIRST_BOX";
export const UNCHECK_SECOND_BOX="UNCHECK_SECOND_BOX";